development:
  adapter: redis

test:
  adapter: redis

production:
  adapter: redis
  url: redis://redistogo:aa5a35d2366b8d57bc2f27c9f4b3a506@scat.redistogo.com:10946/
  #channel_prefix: unstoppable_production
