# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  SECRET_KEY_BASE: <%= ENV["RECAPTCHA_SITE_KEY"] %>
  recaptcha_site_key: <%= ENV["RECAPTCHA_SITE_KEY"] %> # Added line
  recaptcha_secret_key:  <%= ENV["RECAPTCHA_SECRET_KEY"] %> # Added line

test:
  secret_key_base: 359420f2a34e6d3a5d3fd6d0c598eb240f9feb0431c5fc3eb1f1eda32e71536559b67511c62cd9b9b251890787211307f7afc243c077a71f93549307aea722a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["RECAPTCHA_SITE_KEY"] %>
  recaptcha_site_key:  <%= ENV["RECAPTCHA_SITE_KEY"] %> # Added line
  recaptcha_secret_key:  <%= ENV["RECAPTCHA_SECRET_KEY"] %> # Added line
